const constants = {
  ADD_TASK: 'ADD_TASK',
  REMOVE_TASK: 'REMOVE_TASK',
  CLEAR_TASK: 'CLEAR_TASK',
  CHECK_TASK: 'CHECK_TASK',
  UNCHECK_TASK: 'UNCHECK_TASK',
  SET_USER: 'SET_USER',
  REMOVE_USER: 'REMOVE_USER',
  ADD_GOAL: 'ADD_GOAL',
  REMOVE_GOAL: 'REMOVE_GOAL',
  SET_GOAL: 'SET_GOAL',
  CLEAR_GOAL: 'CLEAR_GOAL'
};

export default constants;
