const constants = {
  ADD_ACTIVITY: 'ADD_ACTIVITY',
  REMOVE_ACTIVITY: 'REMOVE_ACTIVITY',
  CLEAR_ACTIVITY: 'CLEAR_ACTIVITY',
  CHECK_ACTIVITY: 'CHECK_ACTIVITY',
  UNCHECK_ACTIVITY: 'UNCHECK_ACTIVITY',
  MOD_ACTIVITY: 'MOD_ACTIVITY',
  REPLACE_ACTIVITY: 'REPLACE_ACTIVITY',
  SET_USER: 'SET_USER',
  REMOVE_USER: 'REMOVE_USER',
  ADD_GOAL: 'ADD_GOAL',
  REMOVE_GOAL: 'REMOVE_GOAL',
  SET_GOAL: 'SET_GOAL',
  CLEAR_GOAL: 'CLEAR_GOAL',
  REPLACE_GOAL: 'REPLACE_GOAL',
  REPLACE_SPORTS: 'CHANGE_SPORTS',
  CLEAR_SPORTS: 'CLEAR_SPORTS',
  REPLACE_GOALTYPE: 'FETCH_GOALTYPE',
  CLEAR_GOALTYPE: 'CLEAR_GOALTYPE',
  FETCH_ACTIVITY: 'FETCH_ACTIVITY',
  CANCEL_FETCHING: 'CANCEL_FETCHING'
};

export default constants;
