const constants = {
  ADD_ACTIVITY: 'ADD_ACTIVITY',
  REMOVE_ACTIVITY: 'REMOVE_ACTIVITY',
  CLEAR_ACTIVITY: 'CLEAR_ACTIVITY',
  CHECK_ACTIVITY: 'CHECK_ACTIVITY',
  UNCHECK_ACTIVITY: 'UNCHECK_ACTIVITY',
  SET_USER: 'SET_USER',
  REMOVE_USER: 'REMOVE_USER',
  ADD_GOAL: 'ADD_GOAL',
  REMOVE_GOAL: 'REMOVE_GOAL',
  SET_GOAL: 'SET_GOAL',
  CLEAR_GOAL: 'CLEAR_GOAL',
  CHANGE_SPORTS: 'CHANGE_SPORTS',
  CLEAR_SPORTS: 'CLEAR_SPORTS'
};

export default constants;
